# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The knapsack problem: brute force algorithm.
#' 
#' @param x an object of class data.frame with two variables v (values) and w (weights).
#' @param head numeric scalar object that represents the knapsack size.
#'
#' @return  \code{brute_force_knapsack} returns a list with two elements: the elements added to the knapsack and the maximum knapsack value.
#'
#' @examples
#' intToBinary(4,8)
#'
#' 
#' @export
intToBinary <- function(x, head) {
    .Call('_knapsack_intToBinary', PACKAGE = 'knapsack', x, head)
}

